name: Cava Tiler PR Diff

on:
  pull_request:
env:
  TITILER_STACK_STAGE: production
  TITILER_STACK_NAME: titiler
  TITILER_STACK_MEMORY: 6016
  AWS_DEFAULT_REGION: us-west-2

jobs:
  cdk-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - name: Install deployment requirements
        run: pip install -r deployment/requirements.txt
      - name: Perform cdk diff
        run: cdk diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
